config/routes.rb
Rails.application.routes.draw do
  
  resources :marking_rules
  resources :categories
  resources :hosts
  resources :reports do
    member do
      get 'show_direct'
    end
  end
  get '/investigation_form', to: "reports#investigation_form"
  post '/investigation_update', to: "reports#investigation_update"
  
  get '/mass_investigation_form', to: "reports#mass_investigation_form"
  post '/mass_investigation_update', to: "reports#mass_investigation_update"
  
  resources :investigation_results
  resources :bugs
  resources :bulids
  resources :versions
  resources :products do
    member do
        post '/report', to: "reports#report_end"
    end
    resources :versions do
      member do
        post '/report', to: "reports#report_end"
      end
      resources :marking_rules
      resources :builds
      resources :hosts
      resources :categories
      resources :reports
      resources :test_cases do 
        resources :reports
      end
    end
  end
  resources :logs
  
  
  root to: "products#index"
  
  get 'static/index'
  get 'static/faq'
  get 'static/reports'
  get 'static/profiles'
  
  resources :global_messages
  get 'global_chat' => 'global_messages#global_chat', as: 'global_chat_log'
  
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords',
        unlocks: 'users/unlocks',
        confirmations: 'users/confirmations',
        #omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  devise_scope :user do
    get 'profile/:id' => 'users/registrations#show', as: 'profile'
    get 'profile/:id/admin_edit' => 'users/registrations#admin_edit_profile', as: 'edit_profile'
    post 'profile/:id/admin_update' => 'users/registrations#admin_update_profile', as: 'update_profile'
  end
  
  
  
  
  resources :examples
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  mount ActionCable.server => '/cable'
  get '/init_chat', to: "global_messages#init_chat"
  
end

app/models/version.rb
class Version
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug
  include Mongoid::Paperclip
  
  field :name, type: String
  slug :name
  
  field :build_name_mutator, type: String
  field :description, type: String
  field :vcs, type: String
  
  belongs_to :product, inverse_of: :version
  has_many :builds, dependent: :destroy
  has_many :test_cases, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :hosts, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :marking_rules, dependent: :destroy
  
  has_mongoid_attached_file :tab_icon
  validates_attachment_content_type :tab_icon, content_type: /\Aimage/
  
  
  
  
  after_create :create_defaults
  
  def create_defaults
    category = Category.new
    category.name = "Default"
    category.description = "Default category"
    category.version = self
    category.save
  end
  
  def to_param
    slug
  end
  
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :set_version, only: [:show, :edit, :update, :destroy]
  before_action :set_product
  
  # GET /versions
  # GET /versions.json
  def index
    @versions = Version.where(product: @product)
    @title=@product.name+' versions'
  end

  # GET /versions/1
  # GET /versions/1.json
  def show
    @title=@version.name
    @slider = true
  end

  # GET /versions/new
  def new
    @version = Version.new
    @title='Adding new version'
  end

  # GET /versions/1/edit
  def edit
    @title='Editing: '+@version.name
  end

  # POST /versions
  # POST /versions.json
  def create
    @version = Version.new(version_params)
    respond_to do |format|
      if @version.save
        format.html { redirect_to product_version_path(@product,@version), notice: 'Version was successfully created.' }
        format.json { render :show, status: :created, location: @version }
      else
        format.html { render :new }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /versions/1
  # PATCH/PUT /versions/1.json
  def update
    respond_to do |format|
      if @version.update(version_params)
        format.html { redirect_to product_version_path(@product,@version), notice: 'Version was successfully updated.' }
        format.json { render :show, status: :ok, location: product_version_path(@product,@version) }
      else
        format.html { render :edit }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /versions/1
  # DELETE /versions/1.json
  def destroy
    @version.destroy
    respond_to do |format|
      format.html { redirect_to product_versions_path(@product), notice: 'Version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_version
      @version = Version.find(params[:id])
    end
    
    def set_product
      if params[:product_id]
        @product = Product.find(params[:product_id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def version_params
      params.require(:version).permit(:name, :description, :vcs, :product_id, :build_name_mutator, :tab_icon )
    end
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/versions/_form.html.erb
<dt>Reporting path:</dt>
<dd><%= report_product_version_path(@product,@version) %></dd>

<%= form_for([@product,@version], html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @version.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@version.errors.count, "error") %> prohibited this version from being saved:</h4>

      <ul>
      <% @version.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
  <%= f.text_field :product_id, class: "invisible" , value: @product._id %>
  
  <div class="form-group row">
      <%= f.label :name, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control" %>
      </div>
  </div>
  <div class="form-group row">
      <%= f.label :build_name_mutator, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :build_name_mutator, class: "form-control" %>
      </div>
  </div>
  <div class="form-group row">
      <%= f.label :description, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :description, class: "form-control" %>
      </div>
  </div>
  <div class="form-group row">
      <%= f.label 'Current version icon', class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
      <% if !@version.tab_icon.nil? %>
        <img src="<%= @version.tab_icon.url %>" alt="">
      <%else%>
        Not uploaded yet
      <% end %>
      </div>
  </div>
  <div class="form-group row">
      <%= f.label 'Upload version icon', class: "col-sm-2 control-label" %> <!--f.label :tab_icon-->
      <div class="col-sm-10">
        <label class="fsLabel btn btn-outline-warning m-x-auto d-block m-t-1">
          <span>Upload</span>
          <%= f.file_field :tab_icon %>
        </label>
      </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
  
<% end %>

app/views/versions/_table.html.erb
<style type="text/css">
table {align-self:left !important;padding-left:45px !important;}
td {height:23px;}
body {font-size:16px;} 
.btn {line-height: 0.8;}
</style>

<% @builds = @version.builds.desc('_id').limit(@number_of_builds).reverse! %>
<% graph_hash = Hash.new{ |h,k| h[k] = Hash.new(&h.default_proc) } %>
<div class="row">
  <!--<div class=col-sm-2></div>-->
  <div style="align-self:left !important;padding-left:80px !important; float:left !important"><!--class=col-sm-8 -->
    <table id="big-mama" class="big-mama table-striped" style="margin: 0 auto; float: none !important;">
    <tbody>
      <% @categories.order(name: :asc).each do |category| %>
        <tr style="font-size:14px;" class="first-col text-cut" id="cat_-<%= category.id %>"><!--width="550px"-->
        <td><!--nr.--></td>
        <td style="text-align:left !important;"><b>&nbsp;<%=link_to category.name,product_version_category_path(@product,@version,category)  %> </b> </td><!--td colspan = 11 -->
      <% builds = @version.builds.desc('_id').limit(@number_of_builds).reverse! %>
      <% builds.each do |build| %>
      <% @version.build_name_mutator.blank? ? link_name=build.name : link_name=eval(@version.build_name_mutator) %>
      <td id="build-<%= build.id %>" class="build-head" width="40px"
      <%= raw("data-toggle=\"tooltip\" data-placement=\"top\" title=\"#{build.description}\"") if !build.description.blank? %>
      ><b><%= link_to link_name, product_version_build_path(@product,@version,build), target: "_blank" %></b></td>
      <% end %>
          </tr>
        <tr>
        <% nr = 1 %>
        <% @version.test_cases.where(category_id: category.id).asc('name').each do |test_case| %>
          <tr id="test_case-<%= test_case.id %>"> 
            <td style="width:30px;font-size:12px;"><%= if nr<10 then nr.to_s.rjust(2,'0') else nr end %></td>
            <td class="first-col text-cut" >&nbsp;<%= link_to test_case.name , product_version_test_case_path(@product,@version,test_case)%></td>
            <% builds.each do |build| %>
              <% if !build.report_links.where(test_case: test_case._id).last.nil? %>
                <% rlink = build.report_links.where(test_case: test_case._id).last %>
                <% if rlink.result %>
                  <% graph_hash[build.name]['passed'].instance_of?(Hash) ? graph_hash[build.name]['passed'] = 1 : graph_hash[build.name]['passed'] += 1 %>
                <% else %>
                  <% graph_hash[build.name]['failed'].instance_of?(Hash) ? graph_hash[build.name]['failed'] = 1 : graph_hash[build.name]['failed'] += 1 %>
                <% end %>
                <td id="cell-<%= rlink.report_id %>"> 
                  <% if current_user.open_in_new_tab%>  
                    <%= render :partial => 'reports/icon', :locals => {:report => rlink } %>  
                  <% else %>
                    <%= render :partial => 'reports/icon_ajax', :locals => {:report => rlink } %>  
                  <% end %>
                </td>
              <% else %>
                <td> </td>
              <% end %>
            <% end %>
          </tr>
          <% nr += 1 %>
        <% end %>
      <% end %>
    </tbody>
  </table>  
  </div>
  <div class=col-sm-2></div>
  
</div>

app/views/versions/edit.html.erb
<div class="container m-t-1 m-b-1">
  <%= link_to product_versions_path(@product), class: 'btn btn-outline-primary pull-md-right m-l-1' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to product_version_path(@product,@version), class: 'btn btn-primary pull-md-right  m-l-1' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>

  <h1>Editing version</h1>
</div>

<%= render 'form' %>

app/views/versions/index.html.erb
<table class="align width">
  <tr><td class="b0 left">
  <h2>Versions</h2>
  </td><td class="b0 right">
  <%= link_to new_product_version_path(@product), class: 'btn btn-outline-primary pull-md-left m-l-1' do %><!--m-x-auto pull-xs-right-->
    <span class="glyphicon glyphicon-plus"></span>
    New Version
  <% end %>
  </td>
  <tr>
</table>

<br><br><br><br>

<div class="table-responsive dl-horizontal">
  <table class="table">
    <thead>
      <tr>
            <th>Name</th>
            <th>Description</th>
            <th></th>
        
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @versions) do |version| %>
            <td style="text-align:left !important;"><%= link_to version.name, product_version_path(@product, version) %></td>
            <td style="text-align:left !important;"><%= version.description %></td>
            <td>
            <%= link_to 'Show', product_version_path(@product, version), class: "btn btn-outline-primary btn-sm" %>
            <%= link_to 'Edit', edit_product_version_path(@product, version), class: "btn btn-primary btn-sm" %>
            <%= link_to 'Destroy', product_version_path(@product, version), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
        </td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/versions/new.html.erb
<div class="container m-t-1 m-b-1">
  <%= link_to versions_path, class: 'btn btn-primary pull-xs-right m-x-auto m-l-1' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New version</h1>
</div>

<%= render 'form' %>

app/views/versions/show.html.erb
<table style="width:1600px !important;margin-left:65px;margin-top:0px;">
  <tr><td class="b0 left">
  <h1>Version: <%= @version.name %></h1>
  </td><td class="b0 right">
  <%= link_to new_product_version_test_case_path(@product,@version), class: 'btn btn-outline-primary pull-md-right m-l-1' do %>
    New test
  <% end %>
  <%= link_to new_product_version_build_path(@product,@version), class: 'btn btn-outline-primary pull-md-right m-l-1' do %>
    New build
  <% end %>
  <%= link_to new_product_version_category_path(@product,@version), class: 'btn btn-outline-primary pull-md-right m-l-1' do %>
    New category
  <% end %>
  <%= link_to edit_product_version_path(@product,@version), class: 'btn btn-primary pull-md-right  m-l-1' do %>
    Edit
  <% end %>
  </td>
  <td class="b0" width="500px"></td>
  <tr>
</table>

<% if current_user.number_of_builds_to_show %>  
  <% @number_of_builds = current_user.number_of_builds_to_show %>
<% else %>
  <% @number_of_builds = 10 %>  
<% end %>



<% @categories = @version.categories.asc('name') %>

<%= render partial: "table", locals: {version: @version, product: @product, number_of_builds: @number_of_builds, categories: @categories } %>
      