config/routes.rb
Rails.application.routes.draw do
  
  resources :marking_rules
  resources :categories
  resources :hosts
  resources :reports do
    member do
      get 'show_direct'
    end
  end
  get '/investigation_form', to: "reports#investigation_form"
  post '/investigation_update', to: "reports#investigation_update"
  
  get '/mass_investigation_form', to: "reports#mass_investigation_form"
  post '/mass_investigation_update', to: "reports#mass_investigation_update"
  
  resources :investigation_results
  resources :bugs
  resources :bulids
  resources :versions
  resources :products do
    member do
        post '/report', to: "reports#report_end"
    end
    resources :versions do
      member do
        post '/report', to: "reports#report_end"
      end
      resources :marking_rules
      resources :builds
      resources :hosts
      resources :categories
      resources :reports
      resources :test_cases do 
        resources :reports
      end
    end
  end
  resources :logs
  
  
  root to: "products#index"
  
  get 'static/index'
  get 'static/faq'
  get 'static/reports'
  get 'static/profiles'
  
  resources :global_messages
  get 'global_chat' => 'global_messages#global_chat', as: 'global_chat_log'
  
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords',
        unlocks: 'users/unlocks',
        confirmations: 'users/confirmations',
        #omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  devise_scope :user do
    get 'profile/:id' => 'users/registrations#show', as: 'profile'
    get 'profile/:id/admin_edit' => 'users/registrations#admin_edit_profile', as: 'edit_profile'
    post 'profile/:id/admin_update' => 'users/registrations#admin_update_profile', as: 'update_profile'
  end
  
  
  
  
  resources :examples
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  mount ActionCable.server => '/cable'
  get '/init_chat', to: "global_messages#init_chat"
  
end

app/models/category.rb
class Category
  include Mongoid::Document
  field :name, type: String
  field :description, type: String
  
  belongs_to :version
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  
  before_action :set_product
  before_action :set_version
  
  skip_before_filter :verify_authenticity_token
  
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.where(version_id: @version)
    @title=@version.name+' categories'
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @title=@category.name
    @slider = true
    @product = @category.version.product
  end

  # GET /categories/new
  def new
    @category = Category.new
    @category.version = @version
    @product = @category.version.product
    @title='Adding new category'
  end

  # GET /categories/1/edit
  def edit
    @title='Editing: '+@category.name
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to product_version_path(@product,@version,@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to product_version_category_path(@product,@version,@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to product_version_categories_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    def set_version
      if params[:version_id]
        @version = Version.find(params[:version_id])
      end
    end
    
    def set_product
      if params[:product_id]
        @product = Product.find(params[:product_id])
      end
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :version_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for([@product,@version,@category], html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @category.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h4>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="form-group row">
       <div class="col-sm-2">Product :</div> 
       <div class="col-sm-10"><%= @product.name %></div>
  </div>
  <div class="form-group row">
       <div class="col-sm-2">Version :</div> 
       <div class="col-sm-10"><%= @version.name %></div>
       <%= f.text_field :version_id , class: "invisible", value: @version._id %>
  </div>
  <div class="form-group row">
    
      <%= f.label :name, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group row">
    
      <%= f.label :description, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :description, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group row">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container m-t-1 m-b-1">
  <%= link_to categories_path, class: 'btn btn-outline-primary pull-md-right m-l-1' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @category, class: 'btn btn-primary pull-md-right  m-l-1' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing category</h1>
</div>

<%= render 'form' %>

app/views/categories/index.html.erb
<table class="align width">
  <tr><td class="b0 left">
  <h2>Categories</h2>
  </td><td class="b0 right">
  <%= link_to new_product_version_category_path(@product,@version), class: 'btn btn-primary pull-xs-right m-x-auto m-l-1' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Category
  <% end %>
  </td>
  <tr>
</table>

<br><br><br><br>

<div class="table-responsive dl-horizontal">
  <table class="table">
    <thead>
      <tr>
            <th>Name</th>
            <th>Description</th>
            <th></th>
        
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @categories) do |category| %>
            <td style="text-align:left !important;"><%= link_to category.name, product_version_category_path(@product,@version,category)  %></td>
            <td><%= category.description %></td>
            <td>
            <%= link_to 'Show', product_version_category_path(@product,@version,category), class: "btn btn-outline-primary btn-sm" %>
            <%= link_to 'Edit', edit_product_version_category_path(@product,@version,category), class: "btn btn-primary btn-sm" %>
            <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
        </td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/categories/new.html.erb
<div class="container m-t-1 m-b-1">
  <%= link_to product_version_path(@product,@version), class: 'btn btn-primary pull-xs-right m-x-auto m-l-1' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New category</h1>
</div>

<%= render 'form' %>

app/views/categories/show.html.erb
<div class="container m-t-1 m-b-1">
  <%= link_to edit_product_version_category_path(@product,@version,@category), class: 'btn btn-primary pull-md-right  m-l-1' do %>
    Edit
  <% end %>
  <h1><%= @category.name %></h1>
</div>

<% @number_of_builds = 10 %>
<% @categories = Category.where(id: @category.id) %>

<%= render partial: "versions/table", locals: {version: @version, product: @product, number_of_builds: @number_of_builds, categories: @categories } %>
      