config/routes.rb
Rails.application.routes.draw do
  
  resources :marking_rules
  resources :categories
  resources :hosts
  resources :reports do
    member do
      get 'show_direct'
    end
  end
  get '/investigation_form', to: "reports#investigation_form"
  post '/investigation_update', to: "reports#investigation_update"
  
  get '/mass_investigation_form', to: "reports#mass_investigation_form"
  post '/mass_investigation_update', to: "reports#mass_investigation_update"
  
  resources :investigation_results
  resources :bugs
  resources :bulids
  resources :versions
  resources :products do
    member do
        post '/report', to: "reports#report_end"
    end
    resources :versions do
      member do
        post '/report', to: "reports#report_end"
      end
      resources :marking_rules
      resources :builds
      resources :hosts
      resources :categories
      resources :reports
      resources :test_cases do 
        resources :reports
      end
    end
  end
  resources :logs
  
  
  root to: "products#index"
  
  get 'static/index'
  get 'static/faq'
  get 'static/reports'
  get 'static/profiles'
  
  resources :global_messages
  get 'global_chat' => 'global_messages#global_chat', as: 'global_chat_log'
  
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords',
        unlocks: 'users/unlocks',
        confirmations: 'users/confirmations',
        #omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  devise_scope :user do
    get 'profile/:id' => 'users/registrations#show', as: 'profile'
    get 'profile/:id/admin_edit' => 'users/registrations#admin_edit_profile', as: 'edit_profile'
    post 'profile/:id/admin_update' => 'users/registrations#admin_update_profile', as: 'update_profile'
  end
  
  
  
  
  resources :examples
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  mount ActionCable.server => '/cable'
  get '/init_chat', to: "global_messages#init_chat"
  
end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug
  include Mongoid::Paperclip
  
  field :name, type: String
  slug  :name
  
  field :description, type: String
  
  has_many :versions, inverse_of: :product, dependent: :destroy
  
  has_mongoid_attached_file :logo
  validates_attachment_content_type :logo, 
                                    :content_type => /^image\/(png|gif|jpeg)/,
                                    :message => 'only (png/gif/jpeg) images'
                                    
  def to_param
    slug
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
      @title=@product.name
  end

  # GET /products/new
  def new
    @product = Product.new
    @title='Adding new product'
  end

  # GET /products/1/edit
  def edit
      @title='Editing: '+@product.name
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :logo)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @product.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h4>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
      <%= f.label :name, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control" %>
      </div>
  </div>
  <div class="form-group row">
      <%= f.label :description, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :description, class: "form-control" %>
      </div>
  </div>
  <div class="form-group row">
      <%= f.label :logo, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <label class="fsLabel btn btn-outline-warning m-x-auto d-block m-t-1">
          <span>Upload</span>
          <%= f.file_field :logo %>
        </label>
      </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="container m-t-1 m-b-1">
  <%= link_to products_path, class: 'btn btn-outline-primary pull-md-right m-l-1' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @product, class: 'btn btn-primary pull-md-right  m-l-1' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing product</h1>
</div>

<%= render 'form' %>

app/views/products/index.html.erb
<style type="text/css">
.container{max-width:1140px;width:1140px;margin-left:50px;}
</style>


<div class="row">


<table style="margin-left:65px;margin-top:7px;margin-bottom:3px;width:1055px !important;">
  <tr><td class="b0 left">
  <h2>Products</h2>
  </td><td class="b0 right">
  <%= link_to new_product_path, class: 'btn btn-primary pull-right m-l-1' do %><!-- pull-xs-right m-x-auto -->
    <span class="glyphicon glyphicon-plus"></span><i class="fa fa-plus" aria-hidden="true"></i>
    New Product
    <% end %>
  </td>
  <tr>
</table>

<br><br><br><br>

  <% @products.each_slice(4) do |group| %>
  <div class="container">
    <div class="row">
    <% group.each do |product| %>
      <div class="col-sm-3" > <!-- class="col-sm-3" style="width:250px"style="width:280px"-->
      <div class="card product-card">
        <%= link_to raw('<img class="card-img-top" src="'+product.logo.url+'" alt="">'), product %>
        <div class="card-block">
          <h4 class="card-title"><%= product.name %></h4>
          <p class="card-text">
            <%= link_to 'Show', product_versions_path(product), class: "btn btn-outline-primary btn-sm" %>
            <%= link_to 'Edit', edit_product_path(product), class: "btn btn-primary btn-sm"%>
            <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
          </p>
        </div>
      </div>
      </div>
    <% end %>
    </div>
  </div>
  <% end %>
  
  
  
</div>

app/views/products/new.html.erb
<div class="container m-t-1 m-b-1">
  <%= link_to products_path, class: 'btn btn-primary pull-xs-right m-x-auto m-l-1' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New product</h1>
</div>

<%= render 'form' %>

app/views/products/show.html.erb
<table class="align width">
  <tr><td class="b0 left">
  <h1>Show product</h1>
  </td><td class="b0 right">
  <%= link_to products_path, class: 'btn btn-outline-primary' do %> 
    Back
  <% end %>
  <%= link_to edit_product_path(@product), class: 'btn btn-primary' do %> 
    Edit
  <% end %>
  </td>
  <tr>
</table>


<br><br><br><br>

<div class="align">
  <dl class="">
  <dt>Name:</dt>
  <dd><%= @product.name %></dd>

  <dt>Description:</dt>
  <dd><%= @product.description %></dd>

  <dt>Reporting path:</dt>
  <dd><%= report_product_path(@product) %></dd>
</dl>

<br>

  <%= link_to new_product_version_path(@product), class: 'btn btn-outline-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Version
  <% end %>

</div>

<br><br>

<div class="table-responsive align">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= content_tag_for(:tr, @product.versions) do |version| %>
        <td class="left">&nbsp;<%= link_to version.name, product_version_path(@product, version) %></td>
        <td class="left">&nbsp;<%= version.description %></td>
        <td>
            <%= link_to 'Show', product_version_path(@product, version), class: "btn btn-outline-primary btn-sm" %>
            <%= link_to 'Edit', edit_product_version_path(@product, version), class: "btn btn-primary btn-sm" %>
            <%= link_to 'Destroy', product_version_path(@product, version), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
        </td>
      <% end %>
    </tbody>
  </table>
</div>