config/routes.rb
Rails.application.routes.draw do
  
  resources :marking_rules
  resources :categories
  resources :hosts
  resources :reports do
    member do
      get 'show_direct'
    end
  end
  get '/investigation_form', to: "reports#investigation_form"
  post '/investigation_update', to: "reports#investigation_update"
  
  get '/mass_investigation_form', to: "reports#mass_investigation_form"
  post '/mass_investigation_update', to: "reports#mass_investigation_update"
  
  resources :investigation_results
  resources :bugs
  resources :bulids
  resources :versions
  resources :products do
    member do
        post '/report', to: "reports#report_end"
    end
    resources :versions do
      member do
        post '/report', to: "reports#report_end"
      end
      resources :marking_rules
      resources :builds
      resources :hosts
      resources :categories
      resources :reports
      resources :test_cases do 
        resources :reports
      end
    end
  end
  resources :logs
  
  
  root to: "products#index"
  
  get 'static/index'
  get 'static/faq'
  get 'static/reports'
  get 'static/profiles'
  
  resources :global_messages
  get 'global_chat' => 'global_messages#global_chat', as: 'global_chat_log'
  
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords',
        unlocks: 'users/unlocks',
        confirmations: 'users/confirmations',
        #omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  devise_scope :user do
    get 'profile/:id' => 'users/registrations#show', as: 'profile'
    get 'profile/:id/admin_edit' => 'users/registrations#admin_edit_profile', as: 'edit_profile'
    post 'profile/:id/admin_update' => 'users/registrations#admin_update_profile', as: 'update_profile'
  end
  
  
  
  
  resources :examples
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  mount ActionCable.server => '/cable'
  get '/init_chat', to: "global_messages#init_chat"
  
end

app/models/build.rb
class Build
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug
  
  field :name, type: String
  slug  :name
  
  field :description, type: String
  
  belongs_to :version
  has_many :reports
  embeds_many :report_links
  
  accepts_nested_attributes_for :report_links
  
  after_create :broadcast
  
  
  def broadcast
    p "Build created"
    ActionCable.server.broadcast 'builds_channel', 
      id: self._id,
      name: self.name
  end
  
end

app/models/report.rb
class Report
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip
  
  field :result, type: Mongoid::Boolean
  field :status, type: String
  field :broken, type: String
  field :url, type: String
  field :error, type: String
  field :total_time, type: String
  field :logs_location, type: String
  field :comment, type: String
  field :custom_params, type: String
  
  has_mongoid_attached_file :screenshot
  validates_attachment_content_type :screenshot, 
                                     :content_type => /^image\/(png|gif|jpeg)/,
                                     :message => 'only (png/gif/jpeg) images'
  
  belongs_to :investigation_result, optional: true
  belongs_to :user, optional: true
  belongs_to :version
  belongs_to :test_case
  belongs_to :build
  belongs_to :host
  
  embeds_many :attachments
  
  paginates_per 100
  
  after_save :link_to_build
  after_create :apply_rules
  after_create :compare_with_prev_build
  after_save :broadcast
  
  accepts_nested_attributes_for :attachments
  
  def broadcast
    ActionCable.server.broadcast 'reports_channel', 
      id: self._id,
      build: self.build_id,
      test_case: self.test_case_id,
      message: render_icon(self)
  end
  
  def link_to_build
    new = true
    if self.build.report_links.where(test_case: self.test_case_id).last.nil? 
      r_link = ReportLink.new() 
    else 
      r_link = self.build.report_links.where(test_case: self.test_case_id).last
      r_link.reruns += 1 
      new = false
    end
    r_link.report_id = self._id
    r_link.result = self.result
    r_link.url = Rails.application.routes.url_helpers.show_direct_report_path(self)
    self.url = r_link.url
    r_link.error = self.error
    r_link.comment = self.comment
    r_link.created_at = self.created_at
    r_link.broken = self.broken if !self.broken.blank?
    r_link.total_time = self.total_time if !self.total_time.blank?
    r_link.investigation_result_id = self.investigation_result_id if !self.investigation_result_id.blank?
    r_link.investigation_result = self.investigation_result.code if !self.investigation_result_id.blank?
    r_link.test_case = self.test_case_id
    r_link.test_case_name = self.test_case.name
    r_link.host = self.host if !self.host.blank?
    new ? self.build.report_links << r_link : r_link.save
    self.build.save

  end
  
  def get_prev_build_last_report
    prev_build = Build.where(:_id.lt => self.build._id).order_by([[:_id, :desc]]).limit(1).first
    if !prev_build.blank?
      prev_report = prev_build.report_links.where(test_case: self.test_case.id).limit(1).first
      if !prev_report.blank?
        prev_report
      else
        nil
      end
    else 
      nil
    end
  end
  
  def investigated?
    self.investigation_result.nil? ? false : true 
  end  
  
  def apply_auto_investigation_rules
    true
  end
  
  def apply_rules
    rules = self.version.marking_rules  
    rules.each do |rule|
      if self.error.include?(rule.pattern)
        self.investigation_result = rule.investigation_result
        self.comment = "Auto-rule: "+rule.name
        self.save
        return ""
      end
    end
      
  end
  
  
  def compare_with_prev_build
    prev_report = get_prev_build_last_report
    if !prev_report.nil?
      if prev_report.error == self.error && prev_report.investigated?
        self.investigation_result = InvestigationResult.find(prev_report.investigation_result_id)
        self.comment = prev_report.comment
        self.save
        "Comparsion applied"
      else
        self.apply_auto_investigation_rules
        ""
      end  
    else
      self.apply_auto_investigation_rules
      ""
    end
  end
  
  def render_icon(report) 
      ApplicationController.new.render_to_string(partial: 'reports/icon', locals: {report: report})
  end
  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy, :show_direct ]
  
  before_action :set_product, only: [:index]
  before_action :set_version, only: [:index]
  
  before_filter :authenticate_user!, only: [:show, :edit, :update, :destroy, :show_direct ]
  
  respond_to :html, :js, :json
  
  layout false, :except => [:edit, :show_direct, :index ]
  
  skip_before_filter :verify_authenticity_token
  
  # GET /reports
  # GET /reports.json
  def index
    @q = Report.where(version_id: @version).ransack(params[:q])
    @q.sorts = 'created_at desc' if @q.sorts.empty?
    @reports = @q.result.page params[:page]
    @slider = true
    @title=@version.name+' reports'
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @version = @report.version
    @product = @version.product
    @hostname = "http://"+request.host+":"+request.port.to_s || "www.mydomain.com"
    @title = @report.test_case.name+' - '+@report.build.name
  end

  def show_direct
    @version = @report.test_case.version
    @product = @version.product
    @hostname = "http://"
    # @hostname = "http://"+request.host+":"+request.port.to_s || "www.mydomain.com"
    @title = @report.test_case.name+' - '+@report.build.name+' - '+@version.name
  end
  
  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
    @title='Editing report'
  end
  
  def investigation_update 
    @report=Report.find(params['report']['report_id'])
    @investigation_status = InvestigationResult.find(params['report']['investigation_result_id'])
    @report.comment = params['report']['comment']
    if !current_user.nil?
      @report.user = current_user
    end
    @report.investigation_result = @investigation_status
    @report.save
  end
  
  def investigation_form 
    @report = Report.find(params[:id])
    render :partial => '/reports/investigation_form'
  end
  
  
  def mass_investigation_update
    eval(params['report']['report_ids']).each do |report_id|
      @report=Report.find(id: report_id.to_s)
      @investigation_status = InvestigationResult.find(params['report']['investigation_result_id'])
      @report.comment = params['report']['comment']
      @report.investigation_result = @investigation_status
      @report.save
    end
  end
  
  def mass_investigation_form 
    @report_ids = params[:id].to_s
    render :partial => '/reports/mass_investigation_form'
  end
  
  
  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def report_end
    @report =  Report.new()
    if @product.nil?
      product = Product.find_by(name: params["product"]) 
    else
      product = @product
    end
    
    if @version.nil?
      version = Version.find_by(name: params["version"])
    else
      version = @version
    end
    
    @report.version = version
    
    if !params["result"].blank?
      @report.result  = (params["result"] == 'passed')
    else
      render text: "ERROR: Result field is blank" and return
    end
    
    if !params["error"].nil?
      @report.error = params["error"]
    else
      render text: "ERROR: Error field is blank" and return
    end
    
    if !params["screenshot"].blank?
      screen_file = Paperclip.io_adapters.for(params["screenshot"])
      screen_file.original_filename = @report.id.to_s+".jpg"
      @report.screenshot = screen_file
    end
    
    if !params["build"].blank?
      if Build.where(version: version, name: params["build"]).exists? 
        @report.build = Build.where(version: version, name: params["build"]).first 
      else
        build = Build.new(name: params["build"], version: version)
        build.save
        @report.build=build
      end
    else
      render text: "ERROR: Build field is blank"  and return
    end
    
    if !params["test_case"].blank?
      if TestCase.where(version: version, name: params["test_case"]).exists? 
        @report.test_case = TestCase.where(version: version, name: params["test_case"]).first 
      else
        test_case = TestCase.new(name: params["test_case"], version: version)
        if !Category.where(version: version).first.blank?
          test_case.category = Category.where(version: version).first
        else
          render text: "ERROR: Create any category for version before reporting"  and return
        end
        if test_case.save
          @report.test_case=test_case
        else
          render text: "ERROR: Unable to save test_case"  and return
        end
      end
    else
      render text: "ERROR: test_case field is blank" and return
    end
    
    if !params["logs_location"].blank?
      @report.logs_location = params["logs_location"]
    end
    
    if !params["broken"].blank?
      @report.broken = params["broken"]
    end
    
    if !params["total_time"].blank?
      @report.total_time = params["total_time"]
    end
    
    if !params["host"].blank?
      if Host.where(version: version, name: params["host"]).exists? 
        @report.host = Host.where(version: version, name: params["host"]).first 
      else
        host = Host.new(name: params["host"], version: version)
        host.save
        @report.host=host
      end
    else
      render text: "ERROR: Host field is blank"  and return
    end
    
    if !params["custom_params"].nil?
      begin
        json = params["custom_params"].to_json
      rescue  
        render text: "ERROR: custom_params is not JSON" and return
      end 
      @report.custom_params = json
    else
      # do something
    end
    if !params["attachments"].blank?
      params["attachments"].each do |k,file|
          file_object = Paperclip.io_adapters.for(file["src"])
          case file['mime_type']
            when /^image\/(png|gif|jpeg|jpg)/
              file_object.original_filename = file['label']+"."+file['mime_type'].split("/")[1]  
            else 
             file_object.original_filename = file['label']+".txt" 
          end
          Attachment.create!(file: file_object, name: file['label'], report: @report, mime_type: file['mime_type'], link: file['link'])
      end
    end

    respond_to do |format|
      if @report.save 
        format.json { render text: "Success: run saved" }
        format.html { render text: "Success: run saved" }
        format.js
      else
        format.json { render json: @report.errors, status: :unprocessable_entity }
        format.html {render :edit }
        format.js
      end
    end
  end

  private
     def set_version
      if params[:version_id]
        @version = Version.find(params[:version_id])
      end
    end
    
    def set_product
      if params[:product_id]
        @product = Product.find(params[:product_id])
      end
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:name, :test_case, :error, :screenshot, :broken, :result, :comment, :custom_params)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @report.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h4>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
      <label class="col-sm-2">Result</label>
      <div class="col-sm-10">
        <div class="form-check m-l-1">
          <%= f.check_box :result, class: "form-check-input" %>
        </div>
      </div>
  </div>
  <div class="form-group row">
      <%= f.label :comment, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :comment, class: "form-control" %>
      </div>
  </div>
  
  <div class="form-group row">
    <%= f.label :custom_params, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">  
      <div class="custom-fields-form">
        <table class="custom-fields-table">
          <thead>
            <th>Name</th>
            <th>Value</th>
            <th></th>
          </thead>
          <tbody class="custom-fields-body">
            <% if !f.object.custom_params.nil? %>
              <% JSON.parse(f.object.custom_params).each do |key| %>
                <tr class="custom-node">
                  <td>
                    <input class="form-control name" type="text" value="<%= key.to_s %>"></input>
                  </td>
                  <td>
                    <input class="form-control value" type="text" value=""></input>
                  </td>
                  <td>
                    <button class="btn btn-sm btn-danger btn-del-custom">-</button>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
        <a class="btn btn-sm btn-primary btn-add-custom">Add field</a>
      </div>
    </div>  
        <%= f.text_field :custom_params, class: "json_holder" %>
  </div>
  <div class="form-group row">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/reports/_icon.html.erb
<style type="text/css">
//a {color:black !important;vertical-align: baseline !important; height:23px !important;}
b {color:black !important;vertical-align: baseline !important;line-height:23px !important;}  
.investigated-code{vertical-align: baseline !important; height:23px !important;}
</style>

<div style="height:23px !important;vertical-align: baseline !important" class="report-icon" id="<%= report.class == Report ? report._id : report.report_id %>" 
    <%= raw("data-toggle=\"tooltip\" data-placement=\"right\" title=\"#{report.comment}\"") if !report.comment.blank? %> >

    <% if report.class == Report %>
        <a href='<%= "/reports/#{report._id}/show_direct" %>' target='_blank' data-no-turbolinks='true' style="height:23px !important;vertical-align: baseline !important">
    <% else %>
        <a href='<%= report.url if !report.url.blank? %>' target='_blank' data-no-turbolinks='true' style="height:23px !important;vertical-align: baseline !important">
    <% end %>



    <% if report.result %>
        <% if report.broken == "true" %>
            <img class="investigated-bg" src="/icons/Diff.png" />
        <% else %>
            <img class="investigated-bg" src="/icons/Passed.png" />
        <% end %>
    <% else %>
        <% if report.investigation_result.nil?%>
            <img class="investigated-bg" src="/icons/Failed.png" />
        <% else %>
            <div class="investigated-code"><b><%= report.investigation_result.class == InvestigationResult ? report.investigation_result.code : report.investigation_result %></b></div>
            <img class="investigated-bg" src="/icons/Warning.png" />
        <% end %>
    <% end %>
    </a>
</div>

app/views/reports/_icon_ajax.html.erb
<div class="report-loader report-icon" id="<%= report.class == Report ? report._id : report.report_id %>" <%= raw("data-toggle=\"tooltip\" data-placement=\"right\" title=\"#{report.comment}\"") if !report.comment.blank? %> >
    <% if report.result %>
        <% if report.broken == "true" %>
            <img class="investigated-bg" src="/icons/Diff.png" />
        <% else %>
            <img class="investigated-bg" src="/icons/Passed.png" />
        <% end %>
    <% else %>
        <% if report.investigation_result.nil?%>
            <img class="investigated-bg" src="/icons/Failed.png" />
        <% else %>
            <div class="investigated-code"><b><%= report.investigation_result.class == InvestigationResult ? report.investigation_result.code : report.investigation_result %></b></div>
            <img class="investigated-bg" src="/icons/Warning.png" />
        <% end %>
    <% end %>
</div>

app/views/reports/_investigation_form.html.erb
<%= form_for( "report", url: investigation_update_path, html: { class: "form-horizontal", role: "form",method: "post" ,remote: true }) do |f| %>
  <div class="form-group row">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :investigation_result_id, InvestigationResult.all.collect {|a| [a.name, a._id]}, {}, {class: "form-control"} %>
    </div>
  </div>  
  <div class="form-group row">
    <%= f.label :comment, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :comment, class: "form-control" %>
      <%= f.text_field :report_id, class: "invisible", value: @report._id %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/reports/_mass_investigation_form.html.erb
<%= form_for( "report", url: mass_investigation_update_path, html: { class: "form-horizontal", role: "form",method: "post" ,remote: true }) do |f| %>
  <div class="form-group row">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :investigation_result_id, InvestigationResult.all.collect {|a| [a.name, a._id]}, {}, {class: "form-control"} %>
    </div>
  </div>  
  <div class="form-group row">
    <%= f.label :comment, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :comment, class: "form-control" %>
      <%= f.text_field :report_ids, class: "invisible", value: @report_ids %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/reports/edit.html.erb
<div class="container m-t-1 m-b-1">
  <%= link_to reports_path, class: 'btn btn-outline-primary pull-md-right m-l-1' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @report, class: 'btn btn-primary pull-md-right   m-l-1' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing report</h1>
</div>

<%= render 'form' %>

app/views/reports/index.html.erb
<table class="align width">
  <tr><td class="b0 left">
  <h2>Reports for <%= @product.name %> <%= @version.name %></h2>
  </td><tr>
</table>

<br><br><br><br>

<div class="container row" style="padding-left:80px">
<%= search_form_for @q , url: product_version_reports_path(@product,@version) ,:html => { :class => "form-inline" } do |f| %>
  <div class="form-group">
    <%= f.label "Error" %>
    <%= f.search_field :error_cont, :class => "form-control" %>
  </div>
  <div class="form-group" style="padding-left:25px">
    <%= f.label "Comment" %>
    <%= f.search_field :comment_cont, :class => "form-control" %>
  </div>
  <div class="form-group" style="padding-left:25px">
    <%= f.label "Custom" %>
    <%= f.search_field :custom_params_cont, :class => "form-control" %>
  </div>
  <div class="form-group col-sm-bottom" style="padding-left:30px">
    <%= f.submit "Search", :class => "btn btn-primary" %>
  </div>
<% end %>
</div>
<br>
<div class="table-responsive" style="padding-left:65px">
    <table class="table table-striped">
      <tr>
        <th></th>
        <th>Test</th>
        <th>Host</th>
        <th>Reported</th>
        <th>Comment</th>
        <th>Error</th>
      </tr>
      <% @reports.each do |report| %>
      <tr>
        <td><%= render :partial => 'reports/icon', :locals => {:report => report } %></td>
        <td style="text-align:left !important;">&nbsp;<%= link_to report.test_case.name, product_version_test_case_path(@product,@version,report.test_case) if !report.test_case.blank?  %></td>
        <td style="text-align:left !important;"><%= link_to report.host.name, product_version_host_path(@product,@version,report.host)  if !report.host.blank?%></td>
        <td style="text-align:left !important;"><%= report.created_at.strftime("%d %B %H:%M") %></td>
        <td><%= report.comment %></td>
        <td class="first-col text-cut"><%= report.error %></td>
      </tr>
      <% end %>
    </table>
</div>
<%= paginate @reports %>

app/views/reports/investigation_update.js.erb
closeModal();
ReloadSlider();

app/views/reports/mass_investigation_update.js.erb
closeModal();

app/views/reports/new.html.erb
<div class="container m-t-1 m-b-1">
  <%= link_to reports_path, class: 'btn btn-primary pull-xs-right m-x-auto m-l-1' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New report</h1>
</div>

<%= render 'form' %>

app/views/reports/show.html.erb
<style type="text/css">
td {border:0px; padding-left: 5px !important;height:22px;}
table {border:0px;} //width:1590px !important; 
</style>

<button id="<%= @report._id %>" class="btn btn-warning pull-md-right m-l-1" onclick='LoadModalWith("/investigation_form",{ id: this.id } )'>Set investigation status</button>
  <%= link_to edit_report_path(@report), class: 'btn btn-primary pull-md-right  m-l-1' do %>Edit<% end %>
<br><br>
<table>

<tr><td width="195px"><div class="text-xs-right"><strong>Product:</strong></div></td>
<td width="450px"><div class="text-xs-left"><%= link_to @report.build.version.product.name, @report.build.version.product %></div></td>

<td rowspan="19" width="945px"><div class="text-xs-right"> <!--805-->
<img class="mx-auto img-err-screen" src="<%= (@report.result or @report.broken == "true") ? "/gif/no_image.gif" : @report.screenshot %>" onclick='enlargeImage(this.src,this.src)' />
</div></td>

<tr><td><div class="text-xs-right"><strong>Version:</strong></div></td>
<td><div class="text-xs-left"><%= link_to @report.build.version.name, product_version_path(@report.build.version.product,@report.build.version) %></div></td></tr>

<tr><td><div class="text-xs-right"><strong>Build:</strong></div></td>
<td><div class="text-xs-left"><%= link_to @report.build.name, product_version_build_path(@report.build.version.product,@report.build.version,@report.build) %></div></td></tr>

<tr><td><div class="text-xs-right"><strong>Host:</strong></div></td>
<td><div class="text-xs-left"><%= @report.host ? (link_to @report.host.name, product_version_host_path(@report.test_case.version.product,@report.test_case.version,@report.host)) : 'N/A'%></div></td></tr>

<tr><td><div class="text-xs-right"><strong>Test case:</strong></div></td>
<td><div class="text-xs-left"><%= link_to @report.test_case.name, product_version_test_case_path(@report.build.version.product,@report.build.version,@report.test_case) %></div></td></tr>

<tr><td><div class="text-xs-right"><strong>Result:</strong></td>
<td><div class="text-xs-left"><%= @report.result ? "Passed" : "Failed"  %></div></td></tr>

<tr><td><div class="text-xs-right"><strong>Broken:</strong></div></td>
<td><div class="text-xs-left"><%= @report.broken ? @report.broken : 'N/A' %></div></td></tr>

<tr><td><div class="text-xs-right"><strong>Reported at:</strong></div></td>
<td><div class="text-xs-left"><%= @report.created_at.strftime("%d %B %H:%M") %></div></td></tr>

<tr><td><div class="text-xs-right"><strong>Total time:</strong></div></td>
<td><div class="text-xs-left"><%= @report.total_time ? @report.total_time : 'N/A'%></div></td></tr>

<tr><td><div class="text-xs-right"><strong>Investigation:</strong></div></td>
<td><div class="text-xs-left"><%= !@report.investigation_result.blank? ? @report.investigation_result.name : 'N/A'%></div></td></tr>

<tr><td><div class="text-xs-right"><strong>Comment:</strong></div></td>
<td><div class="text-xs-left"><%= @report.comment ? @report.comment : 'N/A' %></div></td></tr>

<tr><td><div class="text-xs-right"><strong>Last editor:</strong></div></td>
<td><div class="text-xs-left"><%= @report.user ? @report.user.email : 'N/A'%></div></td></tr>

<tr><td valign="top"><div class="text-xs-right"><strong>Attachments:</strong></div></td>
<td><div class="text-xs-left">
  <% if !@report.attachments.nil? %>
      <div class="text-xs-left">
        <% @report.attachments.each do |attach| %>
          <% case attach.mime_type %>
            <% when "image/jpg" %>
              <span class="tag tag-pill tag-primary">
                <img class="attach-prev m-r-1" onclick='enlargeImage(this.src,this.src)' height=20 width=20 src="<%= attach.file.url %>"/><%= attach.name %>
              </span>
            <% else %>
              <span class="tag tag-pill tag-primary">
                tf<%= attach.name %>
              </span>
            <% end %>
        <% end %>      
              </div>
       <% else %>
  <% end %>
  <%='N/A' if @report.attachments.blank? %>
</div></td></tr>

<tr><td>&nbsp;</td></tr>
<tr><td>&nbsp;</td></tr>
<tr><td>&nbsp;</td></tr>
<tr><td>&nbsp;</td></tr>

</table>

<table>

<tr><td><div class="text-xs-right"><strong>Direct link:</strong></div></td>
<td><div class="text-xs-left"><%= link_to @hostname+show_direct_report_path(@report).to_s, show_direct_report_path(@report), :target => "_blank" %></div></td></tr>

<tr><td width="195px"><div class="text-xs-right"><strong>Logs:</strong></div></td>
<td width="1400px"><div class="text-xs-left"><% if !@report.logs_location.nil? %><a href="file://<%= @report.logs_location %>"><%= @report.logs_location %></a><% end %></div></td></tr>

<tr><td valign="top"><div class="text-xs-right"><strong>Error:</strong></div></td>
<td><div class="text-xs-left"><%= !@report.error.blank? ? @report.error : 'N/A' %></div></td></tr>


</table>
<br>&nbsp;<br>
<table>
<tr><td>&nbsp;</td></tr>
<tr><td width="195px"><div class="text-xs-right"><strong>Сustom_params:</strong></div></td>
<td><div class="text-xs-left"></div></td></tr>

<% if JSON.parse(@report.custom_params) %>
  <% cp = JSON.parse(@report.custom_params)%>
  <div class="<%= cp['data_type'] %>">
    <%= render :partial => 'data_types/'+cp['data_type'], :locals => {:data => cp} %>
  </div>
<% else %>
    Custom params are not json
    <%= @report.custom_params%>
<% end %>

<div id="largeImgPanel" onclick="this.style.display='none'">
  <img id="largeImg" />
</div>

</table>

app/views/reports/show_direct.html.erb
<%= render :template => "reports/show", :locals => {:report => @report} %>